AdobeProduct.create(name: "Adobe AfterEffects", mnemonic_file_name: "aftereffects.png", mnemonic_content_type: "image/png", mnemonic_file_size: 1693)
AdobeProduct.create(name: "Adobe Dreamweaver", mnemonic_file_name: "dreamweaver.png", mnemonic_content_type: "image/png", mnemonic_file_size: 3406)
AdobeProduct.create(name: "Adobe Illustrator", mnemonic_file_name: "illustrator.png", mnemonic_content_type: "image/png", mnemonic_file_size: 1677)
AdobeProduct.create(name: "Adobe InDesign", mnemonic_file_name: "indesign.png", mnemonic_content_type: "image/png", mnemonic_file_size: 1583)
AdobeProduct.create(name: "Adobe Muse", mnemonic_file_name: "muse.png", mnemonic_content_type: "image/png", mnemonic_file_size: 1593)
AdobeProduct.create(name: "Adobe Photoshop", mnemonic_file_name: "photoshop.png", mnemonic_content_type: "image/png", mnemonic_file_size: 1626)
AdobeProduct.create(name: "Adobe Premiere", mnemonic_file_name: "premiere.png", mnemonic_content_type: "image/png", mnemonic_file_size: 1631)
