Post.create(text: "This is a first post.")
Post.create(text: "This is a second post.")
Post.create(text: "This is a third post.")
Post.create(text: "This is a fourth post.")
Post.create(text: "This is a fifth post.")
Post.create(text: "This is a sixth post.")
Post.create(text: "This is a seventh post.")
Post.create(text: "This is a eighth post.")
Post.create(text: "This is a ninth post.")
Post.create(text: "This is a tenth post.")
Post.create(text: "This is a eleventh post.")
Post.create(text: "This is a twelfth post.")
Post.create(text: "This is a thirteenth post.")
Post.create(text: "This is a fourteenth post.")
Post.create(text: "This is a fifteenth post.")
Post.create(text: "This is a sixteenth post.")
Post.create(text: "This is a seventeenth post.")
Post.create(text: "This is a eighteenth post.")
Post.create(text: "This is a nineteenth post.")
Post.create(text: "This is a twentieth post.")
Post.create(text: "This is twenty-first post.")
Post.create(text: "This is twenty-second post.")
Post.create(text: "This is twenty-third post.")
Post.create(text: "This is twenty-fourth post.")
Post.create(text: "This is twenty-fifth post.")
Post.create(text: "This is twenty-sixth post.")
Post.create(text: "This is twenty-seventh post.")
Post.create(text: "This is twenty-eighth post.")
Post.create(text: "This is twenty-ninth post.")
Post.create(text: "This is thirtieth post.")

User.find(4).posts << Post.find(1)
User.find(5).posts << Post.find(2)
User.find(6).posts << Post.find(3)
User.find(7).posts << Post.find(4)
User.find(4).posts << Post.find(5)
User.find(5).posts << Post.find(6)
User.find(6).posts << Post.find(7)
User.find(7).posts << Post.find(8)
User.find(4).posts << Post.find(9)
User.find(5).posts << Post.find(10)
User.find(6).posts << Post.find(11)
User.find(7).posts << Post.find(12)
User.find(4).posts << Post.find(13)
User.find(5).posts << Post.find(14)
User.find(6).posts << Post.find(15)
User.find(7).posts << Post.find(16)
User.find(4).posts << Post.find(17)
User.find(5).posts << Post.find(18)
User.find(6).posts << Post.find(19)
User.find(7).posts << Post.find(20)
User.find(4).posts << Post.find(21)
User.find(5).posts << Post.find(22)
User.find(6).posts << Post.find(23)
User.find(7).posts << Post.find(24)
User.find(4).posts << Post.find(25)
User.find(5).posts << Post.find(26)
User.find(6).posts << Post.find(27)
User.find(7).posts << Post.find(28)
User.find(4).posts << Post.find(29)
User.find(5).posts << Post.find(30)
